adam_beta1: 0.9
adam_beta2: 0.98
adam_epsilon: 1.0e-06
bf16: true
dataset: Qwen2-VL-geoqa
ddp_timeout: 180000000
do_train: true
eval_steps: 500
eval_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 8
learning_rate: 3.0e-05
logging_steps: 10
lora_target: all
lr_scheduler_type: constant_with_warmup
max_length: 2048
model_name_or_path: Qwen2-VL-7B-Instruct
num_train_epochs: 3.0
output_dir: saves/Qwen2-VL-sft
overwrite_cache: true
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
save_strategy: epoch
save_total_limit: 10
stage: sft
template: qwen2_vl
val_size: 0.1
warmup_ratio: 0.1
weight_decay: 0.05
